[chain]
chain_id = "rømer-devnet-1"
version = "0.1.0"
genesis_timestamp = 1703433600  # December 24, 2024 UTC
block_target_seconds = 30
epoch_length_blocks = 1000

[chain.constraints]
max_block_size_bytes = 1048576        # 1MB maximum block size
max_transaction_size_bytes = 65536     # 64KB maximum transaction size
max_transactions_per_block = 1000
max_block_gas_limit = 30000000        # Maximum computational resources per block

[validators]
minimum_validators = 1
maximum_validators = 100

[validators.hardware]
minimum_cpu_cores = 8
minimum_ram_gb = 32
minimum_storage_tb = 4
minimum_bandwidth_mbps = 1000         # 1 Gbps minimum network connection

[validators.network]
# Geographic and network requirements for validators
minimum_regions = 3                    # Minimum distinct regions required
maximum_per_region = 10               # Maximum validators per region
minimum_region_distance_km = 1000     # Minimum distance between validators
maximum_latency_ms = 100              # Maximum allowed network latency
required_path_diversity = 3           # Required distinct network paths

[validators.performance]
minimum_uptime_percent = 99.9
performance_evaluation_blocks = 1000   # Blocks to evaluate performance over
maximum_missed_blocks = 10            # Per evaluation period
maximum_response_time_ms = 50         # Maximum time to respond to requests

[tokenomics]
token_name = "RØMER"
token_symbol = "ROMER"
decimals = 2                          # Smallest unit (1 Ole = 0.01 RØMER)
smallest_unit_name = "Ole"            # Named after Ole Rømer

[tokenomics.supply]
initial_supply_ole = 30000000         # 300,000 RØMER in smallest units

[tokenomics.addresses]
treasury = "3eec2d691ee2952ff9924a0db1db24c356d38a8e16b0e4b2b6f1a6a15588e112"
burn = "0000000000000000000000000000000000000000000000000000000000000000"

[tokenomics.distribution]
treasury_allocation_ole = 30000000    # Initial treasury allocation

[tokenomics.rewards]
base_block_reward_ole = 100           # 1 RØMER per block in Ole units
transaction_fee_minimum_ole = 10      # Minimum transaction fee
storage_deposit_ole_per_byte = 1      # Storage deposit per byte

[tokenomics.adjustments]
reward_adjustment_period_blocks = 10080    # One week of blocks
minimum_blocks_for_adjustment = 5040       # Half week minimum
utilization_low_threshold = 25             # Percent of target
utilization_high_threshold = 100           # Percent of target
maximum_reward_adjustment_percent = 10      # Maximum change per period

[regions]
# Definition of recognized geographic regions
[regions.oceania]
name = "Oceania"
required_countries = ["Australia", "New Zealand"]
minimum_validators = 1

[regions.asia]
name = "Asia"
required_countries = ["Japan", "Singapore", "South Korea"]
minimum_validators = 1

[regions.europe]
name = "Europe"
required_countries = ["Germany", "Netherlands", "France"]
minimum_validators = 1

[regions.americas]
name = "Americas"
required_countries = ["United States", "Canada", "Brazil"]
minimum_validators = 1

[infrastructure]
# Infrastructure verification and monitoring parameters
hardware_verification_interval_blocks = 1000
network_path_verification_blocks = 100
geographic_reverification_blocks = 10000
proof_of_location_threshold_m = 1000      # Maximum allowed location drift
minimum_infrastructure_proof_bits = 1024   # Minimum proof complexity