# Rømer Chain Commonware Runtime Configuration

[runtime]
# Choose between production, testing, or development environments
environment = "development"

[executor]
# Configurable runtime executor settings
default_timeout_ms = 30000  # 30-second default timeout
max_task_retries = 3
task_retry_delay_ms = 1000

[network]
# Network-related runtime configurations
connection_timeout_ms = 5000
max_concurrent_connections = 50
keepalive_interval_ms = 30000

[storage]
# Storage-related runtime configurations
default_partition = "dev"
max_open_blobs = 10
blob_sync_interval_ms = 5000
default_compression_level = 3

[performance]
# Performance tuning parameters
max_spawn_concurrency = 4
spawn_queue_size = 128
task_scheduling_strategy = "dynamic"  # Options: static, dynamic, adaptive

[fault_tolerance]
# Fault tolerance and recovery configurations
max_task_failures = 5
auto_recovery_enabled = true
recovery_strategy = "restart"  # Options: restart, fallback, abort

[logging]
# Runtime logging configurations
log_level = "info"  # Options: error, warn, info, debug, trace
log_format = "json"
max_log_file_size_mb = 50
max_log_files = 5

[metrics]
# Prometheus-compatible metrics configuration
metrics_enabled = true
metrics_port = 9000
metrics_path = "/metrics"
prometheus_namespace = "romer_runtime"

[deterministic]
# Configuration specific to deterministic runtime mode
seed = 0  # Use 0 for true randomness, or set a specific seed for reproducibility
max_deterministic_tasks = 100