[runtime]
# Environment selection reflects system's current development stage
environment = "development"

[runtime.development]
# Deterministic seed allows reproducible network simulations
# Useful for testing consensus and network behaviors
seed = 42  # Arbitrary but consistent seed for deterministic execution
cycle = 30  # Block time in seconds, matches network design
timeout = 60000  # 60 second overall operation timeout

[runtime.production]
# Production settings prioritize stability and performance
threads = 8  # Matches minimum node CPU requirement 
catch_panics = true  # Graceful error handling critical for network stability
read_timeout = 5000  # 5 second read timeout prevents network stalls
write_timeout = 5000  # 5 second write timeout ensures transaction reliability
tcp_nodelay = true  # Reduces network latency for consensus messages
storage_directory = "/var/lib/romer/storage"  # Standard Unix system path 
maximum_buffer_size = 67108864  # 64MB, balances memory usage and performance