# RØMER Chain Tokenomics Configuration
# All monetary parameters for the network's native token

[token]
name = "RØMER"
symbol = "ROMER"
decimals = 2  # Smallest unit (1 Ole = 0.01 RØMER)
smallest_unit_name = "Ole"  # Named after Ole Rømer

[supply]
# Initial supply set to speed of light in km
# 300,000 RØMER = 30,000,000 Ole
initial_supply = 30000000  # In smallest units (Ole)

[addresses]
treasury = "3eec2d691ee2952ff9924a0db1db24c356d38a8e16b0e4b2b6f1a6a15588e112"
burn = "0000000000000000000000000000000000000000000000000000000000000000"

[distribution]
# Initial token distribution at genesis
treasury_allocation = 30000000  # 100% to treasury initially

[block_rewards]
# Base block reward for validators
base_reward = 100  # 1 RØMER per block in Ole units

[network_policy]
# Network utilization parameters that influence monetary policy
target_transactions_per_block = 50
adjustment_period_blocks = 10080  
utilization_thresholds = { low = 25, high = 100 }  # Transactions per block thresholds
reward_adjustments = { burn = -100, mint = 100 }  # ±1 RØMER in Ole units

[network_metrics]
# Parameters for tracking network health
metrics_window_blocks = 10080  
min_blocks_for_adjustment = 5040 
update_frequency_blocks = 10080  